trigger:
  branches:
    include:
    - Temp_Changes
    - testBranch
variables:
  solution: test.sln
  buildPlatform: x86
  buildConfiguration: Release
  imageName: windows-latest
  projectPath: ''
  artifactName: Ideploy-Drop
pool:
  vmImage: $(imageName)
steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: $(solution)
- task: VSBuild@1
  inputs:
    solution: $(solution)
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Pipeline.Workspace)
    artifactType: pipeline
    artifactName: $(artifactName)
