trigger:
  branches:
    include:
    - master
    - testBranch
variables:
  buildPlatform: x64
  imageName: ubuntu-18.04
  artifactName: Test-drop
  gradleOption: -Xmx3072m
  jdkVersion: 1.8
  gradleFile: gradlew
  contentPath: '**/target/*.jar'
  option: ''
  pomPath: pom.xml
  mavenOption: -Xmx3072m
  goals: package
pool:
  vmImage: $(imageName)
steps:
- task: Gradle@2
  inputs:
    workingDirectory: ' '
    gradleWrapperFile: $(gradleFile)
    gradleOptions: $(gradleOption)
    javaHomeOption: JDKVersion
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: $(buildPlatform)
    publishJUnitResults: false
    tasks: build
- task: CopyFiles@2
  inputs:
    contents: $(contentPath)
    targetFolder: $(build.artifactStagingDirectory)
- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    artifactName: $(artifactName)
    pathToPublish: $(build.artifactStagingDirectory)
